import { useState, type ReactNode } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { native } from "../lib/native";
import { DEFAULT_PREFERENCES, shortcutFromEvent, shortcutLabel, type Preferences } from "../lib/preferences";

type Section = "appearance" | "panel" | "keyboard" | "interface" | "workspace" | "startup";
const sections: Array<[Section, string]> = [["appearance", "Appearance"], ["panel", "Panel & activation"], ["keyboard", "Keyboard"], ["interface", "Interface"], ["workspace", "Workspace & lock"], ["startup", "Startup"]];
function Field({ label, description, children }: { label: string; description?: string; children: ReactNode }) { return <div className="settings-field"><div><strong>{label}</strong>{description && <p>{description}</p>}</div>{children}</div>; }
function Toggle({ checked, onChange, label }: { checked: boolean; onChange: (checked: boolean) => void; label: string }) { return <label className="settings-toggle"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><span aria-hidden="true" /><b>{label}</b></label>; }
function ShortcutInput({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <input className="shortcut-recorder" aria-label="Shortcut" readOnly value={shortcutLabel(value)} onKeyDown={(event) => { event.preventDefault(); const next = shortcutFromEvent(event); if (next) onChange(next); }} />; }

/** A full-page preferences view. It occupies Sonata's panel, not the desktop. */
export function SettingsPanel({ close, onLock }: { close: () => void; onLock: () => void }) {
  const qc = useQueryClient(); const [section, setSection] = useState<Section>("appearance"); const [busy, setBusy] = useState<"workspace" | "index">(); const [message, setMessage] = useState<string>(); const [password, setPassword] = useState(""); const [timeout, setTimeoutMinutes] = useState(15);
  const preferences = useQuery({ queryKey: ["preferences"], queryFn: native.preferences, retry: false }); const lock = useQuery({ queryKey: ["workspace-lock"], queryFn: native.workspaceLockStatus }); const prefs = preferences.data ?? DEFAULT_PREFERENCES;
  const autostart = useQuery({ queryKey: ["autostart"], queryFn: native.autostartEnabled, retry: false });
  const save = async (next: Preferences) => { setMessage(undefined); try { await native.savePreferences(next); await qc.invalidateQueries({ queryKey: ["preferences"] }); } catch (error) { setMessage(String(error)); } };
  const update = (patch: Partial<Preferences>) => void save({ ...prefs, ...patch });
  const updateShortcuts = (patch: Partial<Preferences["shortcuts"]>) => { const next = { ...prefs, shortcuts: { ...prefs.shortcuts, ...patch } }; const all = [next.shortcuts.search, next.shortcuts.palette, next.shortcuts.capture, next.shortcuts.newNote, next.panelShortcut].filter(Boolean).map((key) => String(key).toLowerCase()); if (new Set(all).size !== all.length) { setMessage("Each Sonata shortcut must be unique."); return; } void save(next); };
  const run = async (kind: "workspace" | "index", action: () => Promise<unknown>) => { setBusy(kind); setMessage(undefined); try { await action(); await qc.invalidateQueries(); setMessage(kind === "workspace" ? "Workspace opened" : "Search index rebuilt"); } catch (error) { setMessage(String(error)); } finally { setBusy(undefined); } };
  const resetSection = () => { if (section === "startup") { void native.setAutostart(false).then(() => qc.invalidateQueries({ queryKey: ["autostart"] })); return; } if (section === "workspace") { setMessage("Workspace and lock settings are intentionally not changed by a personal-settings reset."); return; } const d = DEFAULT_PREFERENCES; const next: Preferences = section === "appearance" ? { ...prefs, theme: d.theme, accent: d.accent, density: d.density, motion: d.motion } : section === "panel" ? { ...prefs, hoverEnabled: d.hoverEnabled, autoHide: d.autoHide, hoverDelayMs: d.hoverDelayMs, pauseHoverFullscreen: d.pauseHoverFullscreen, panelShortcut: d.panelShortcut } : section === "keyboard" ? { ...prefs, shortcuts: d.shortcuts } : { ...prefs, showTags: d.showTags, showQuickAdd: d.showQuickAdd }; void save(next); };
  const content = () => {
    if (section === "appearance") return <><h2>Appearance</h2><p className="settings-intro">Make Sonata feel at home without changing your notes or workspace.</p><Field label="Theme"><div className="settings-options">{(["system", "light", "dark"] as const).map((value) => <button className={prefs.theme === value ? "selected" : ""} key={value} onClick={() => update({ theme: value })}>{value}</button>)}</div></Field><Field label="Accent"><div className="settings-options">{(["green", "blue", "violet", "amber"] as const).map((value) => <button className={`accent-${value} ${prefs.accent === value ? "selected" : ""}`} key={value} onClick={() => update({ accent: value })}><i />{value}</button>)}</div></Field><Field label="Density" description="Compact reduces browsing spacing, not document content."><div className="settings-options">{(["comfortable", "compact"] as const).map((value) => <button className={prefs.density === value ? "selected" : ""} key={value} onClick={() => update({ density: value })}>{value}</button>)}</div></Field><Field label="Motion"><div className="settings-options">{(["system", "reduced"] as const).map((value) => <button className={prefs.motion === value ? "selected" : ""} key={value} onClick={() => update({ motion: value })}>{value}</button>)}</div></Field></>;
    if (section === "panel") return <><h2>Panel & activation</h2><p className="settings-intro">Use hover, a global shortcut, the tray, or a mix of them.</p><Field label="Right-edge hover" description="Hover the center of the right screen edge to reveal Sonata."><Toggle label="Enable hover activation" checked={prefs.hoverEnabled} onChange={(hoverEnabled) => update({ hoverEnabled })} /></Field><Field label="Auto-hide"><Toggle label="Hide after the pointer leaves Sonata" checked={prefs.autoHide} onChange={(autoHide) => update({ autoHide })} /></Field><Field label="Leave delay"><select aria-label="Leave delay" value={prefs.hoverDelayMs} onChange={(event) => update({ hoverDelayMs: Number(event.target.value) as 150 | 250 | 500 })}><option value={150}>Short</option><option value={250}>Standard</option><option value={500}>Relaxed</option></select></Field><Field label="Fullscreen-app pause" description="Windows only. Tray and shortcuts still work."><Toggle label="Pause hover around fullscreen apps" checked={prefs.pauseHoverFullscreen} onChange={(pauseHoverFullscreen) => update({ pauseHoverFullscreen })} /></Field><Field label="Global panel toggle" description="Works when Sonata is hidden. Leave blank to use hover and tray only."><ShortcutInput value={prefs.panelShortcut ?? ""} onChange={(panelShortcut) => update({ panelShortcut })} />{prefs.panelShortcut && <button className="text-button" onClick={() => update({ panelShortcut: null })}>Remove shortcut</button>}</Field></>;
    if (section === "keyboard") return <><h2>Keyboard</h2><p className="settings-intro">These work while Sonata is focused. Click a field, then press a key combination.</p>{([ ["search", "Focus search"], ["palette", "Open command palette"], ["capture", "Focus quick add"], ["newNote", "Create new note"] ] as const).map(([key, label]) => <Field key={key} label={label}><ShortcutInput value={prefs.shortcuts[key]} onChange={(value) => updateShortcuts({ [key]: value })} /></Field>)}</>;
    if (section === "interface") return <><h2>Interface</h2><p className="settings-intro">Keep the panel focused on the tools you use most.</p><Field label="Tag chips" description="Shows the tag bar below the toolbar."><Toggle label="Show tag chips" checked={prefs.showTags} onChange={(showTags) => update({ showTags })} /></Field><Field label="Quick add" description="Hides the pinned composer until its shortcut is used."><Toggle label="Show quick add" checked={prefs.showQuickAdd} onChange={(showQuickAdd) => update({ showQuickAdd })} /></Field></>;
    if (section === "startup") return <><h2>Startup</h2><p className="settings-intro">Start Sonata with your computer so it is always one gesture away.</p><Field label="Launch at login" description="Registers Sonata with your operating system; it does not open or change a workspace."><Toggle label="Start Sonata automatically" checked={autostart.data ?? false} onChange={(enabled) => { void native.setAutostart(enabled).then(() => qc.invalidateQueries({ queryKey: ["autostart"] })).catch((error) => setMessage(String(error))); }} /></Field></>;
    return <><h2>Workspace & session lock</h2><p className="settings-intro">Your Markdown stays portable. These settings apply only to the chosen workspace.</p><Field label="Workspace"><button className="primary" disabled={busy !== undefined} onClick={() => void run("workspace", native.chooseWorkspace)}>Choose workspace…</button><button disabled={busy !== undefined} onClick={() => void run("index", native.rebuild)}>Rebuild search index</button></Field><Field label="Session lock" description="Protects Sonata after inactivity; Markdown files remain unencrypted and portable."><input aria-label="Lock password" type="password" value={password} placeholder={lock.data?.enabled ? "New password, or blank to disable" : "Set a password"} onChange={(event) => setPassword(event.target.value)} /><label className="settings-timeout">Lock after <input aria-label="Lock timeout minutes" type="number" min="1" max="240" value={timeout} onChange={(event) => setTimeoutMinutes(Number(event.target.value))} /> minutes</label><button disabled={busy !== undefined} onClick={() => void run("index", async () => { await native.configureWorkspaceLock(password, timeout); await qc.invalidateQueries({ queryKey: ["workspace-lock"] }); setPassword(""); })}>{lock.data?.enabled ? "Save lock settings" : "Enable lock"}</button>{lock.data?.enabled && <button onClick={() => { onLock(); close(); }}>Lock now</button>}</Field></>;
  };
  return <main className="settings-page"><header className="settings-page-header"><button className="icon-btn" aria-label="Close settings" onClick={close}>×</button><div><p className="eyebrow">SONATA</p><h1>Settings</h1></div><button className="text-button" onClick={resetSection}>Reset section</button></header><div className="settings-layout"><nav aria-label="Settings sections">{sections.map(([id, label]) => <button key={id} className={section === id ? "active" : ""} onClick={() => setSection(id)}>{label}</button>)}<button className="settings-reset-all" onClick={() => { if (window.confirm("Reset all personal settings to Sonata defaults?")) void native.resetPreferences().then(() => qc.invalidateQueries({ queryKey: ["preferences"] })); }}>Reset all settings</button></nav><section className="settings-content">{content()}{message && <p role="status" className="settings-status">{message}</p>}</section></div></main>;
}
